kwinctl: Prevent whole script from crashing when there are tiled windows
The actual problem is that candidate windows are attached directly to
rule objects which are then `JSON.stringify`ed. However, tiled windows
carry the Tile object with them, which in turn contains other windows
related to that tile, which then refer to the first window thus
creating circular object which resulted in error such as:
```
kwin_wayland[4824]: /tmp/kwinctl-vleqljo9.js:208: error: Cannot convert circular structure to JSON
```